# Generated by Django 5.0.1 on 2024-02-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_alter_venda_data_de_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
