# Generated by Django 5.0.1 on 2024-02-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_venda_desconto_orcamento_budgetproposalitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='desconto',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='produtos',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='budgetproposalitem',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
