# Generated by Django 5.0.1 on 2024-02-07 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='ordem_de_compra',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='ingredientes',
        ),
    ]
