# Generated by Django 5.0.1 on 2024-02-09 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorio', '0002_remove_ingrediente_ordem_de_compra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='produtos',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='ingredients',
        ),
    ]
