# Generated by Django 5.0.1 on 2024-02-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorio', '0004_alter_ingrediente_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienteordemdecompra',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produtoingrediente',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
